-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.tag
(
    tag_id serial,
    name text,
    category text,
    PRIMARY KEY (tag_id)
);

CREATE TABLE IF NOT EXISTS public.item
(
    item_id serial,
    description text,
    image_source text,
    price double precision,
    PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public.tag_item
(
    tag_tag_id serial,
    item_item_id serial,
    id serial,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.role
(
    role_id serial,
    name text,
    PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    user_id serial,
    username character varying(30),
    password character varying(250),
    first_name text,
    last_name text,
    phone text,
    email text,
    address text,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.role_tag
(
    role_role_id serial,
    tag_tag_id serial,
    id serial,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."order"
(
    order_id serial,
    status text,
    PRIMARY KEY (order_id)
);

CREATE TABLE IF NOT EXISTS public.order_item
(
    order_order_id serial,
    item_item_id serial,
    id serial,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_tag
(
    user_user_id serial,
    tag_tag_id serial
);

ALTER TABLE IF EXISTS public.tag_item
    ADD FOREIGN KEY (tag_tag_id)
    REFERENCES public.tag (tag_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.tag_item
    ADD FOREIGN KEY (item_item_id)
    REFERENCES public.item (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."user"
    ADD FOREIGN KEY (user_id)
    REFERENCES public.role (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.role_tag
    ADD FOREIGN KEY (role_role_id)
    REFERENCES public.role (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.role_tag
    ADD FOREIGN KEY (tag_tag_id)
    REFERENCES public.tag (tag_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."order"
    ADD FOREIGN KEY (order_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.order_item
    ADD FOREIGN KEY (order_order_id)
    REFERENCES public."order" (order_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.order_item
    ADD FOREIGN KEY (item_item_id)
    REFERENCES public.item (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_tag
    ADD FOREIGN KEY (user_user_id)
    REFERENCES public."user" (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.user_tag
    ADD FOREIGN KEY (tag_tag_id)
    REFERENCES public.tag (tag_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;